language: cpp
sudo: false
cache: ccache
script: cmake

#matrix:
  #include:
    #- os: linux
      #addons:
        #apt:
          #sources:
            #- ubuntu-toolchain-r-test
          #packages:
            #- cmake
            #- g++-7
      #env:
        #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    #- os: linux
      #addons:
        #apt:
          #sources:
            #- llvm-toolchain-trusty-5.0
          #packages:
            #- cmake
            #- clang-5.0
      #env:
        #- MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo pip install cmake
  - which $CXX
  - which $CC
  - which cmake
  - cmake --version
